apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: shivkanyadoiphode/microservicesdeployment-api:latest
          ports:
            - containerPort: 4000 # match app-config PORT
          env:
            # ConfigMap values
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PORT
            - name: CORS_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: CORS_ORIGIN
            # DB values from Secret
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DATABASE
            # Static values
            - name: DB_HOST
              value: db
            - name: DB_PORT
              value: "3306"
          # No need to override args if PORT is from env
          command: ["node", "server.js"]

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: api
spec:
  selector:
    app: api
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 4000 # cluster-wide port
      targetPort: 4000 # container port
      nodePort: 32370 # stable NodePort for Minikube
