apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA==      # root
  MYSQL_DATABASE: YXBpZGI=           # apidb
  MYSQL_USER: YXBpdXNlcg==           # apiuser
  MYSQL_PASSWORD: YXBpcGFzcw==       # apipass

